# Tùy bạn nhé | Seek your self
Selector-Support: true

# Chọn vật phẩm cần dùng cho việc chọn máy chủ | Choose what item the server selector should be
Selector-Item: 345

# This is the text that will show on the selector in the player's inventory!
# Đây là của Việt Nam | This is Vietnamese version
Selector-Name: "§l§aLa bàn Máy Chủ"

# Đây là phần tiêu đề của UI | This is the title of the server UI
UI-Title: "§9Danh sách máy chủ"

# Đây là phần lời nhắn sẽ hiện bên dưới tiêu đề của UI | This is the message the will show under your title on the server UI
UI-Message: "§aHãy chọn 1 máy chủ!"

# Đây là danh sách các máy chủ mà bạn muốn hiển thị trên UI | This is where you list your servers to be displayed on the server UI
# Bạn có thể sử dụng '§' hoặc '&' ở phần dưới để thay đổi màu sắc hiển thị bên trong UI | You can use '§' and '&' on the labels to colorize your servers inside the UI!
# Về hình ảnh, hãy dùng 'url' hoặc 'path' để hiển thị hình ảnh trong phần chọn máy chủ (có thể bỏ trống hoặc ko sử dụng nhé) | For images, use 'url' or 'path' to show an image in the menus (or leave blank to disable)
# Lưu ý: Nếu bạn muốn sư dụng 1 đường dẫn, KO được chứa 'https://' hoặc 'http://' trong phần đường dẫn! | Note: If you are using a URL, do NOT include the 'https://' or 'http://' in the link!
# Mẫu: Tên máy chủ:IP máy chủ:Port:url:Đường dẫn file trong máy chủ/Đường dẫn trên mạng | Example format → ServerName:ServerIP:ServerPort:ImageType:Path/URL
Servers:
  - "&l&6Lobby §eServer:kora.ddns.net:19132:url:i.imgur.com/bgoM5jd.png"
  - "§l&2Prison §eServer:kora.ddns.net:19133:url:i.imgur.com/lLJWjfr.png"
  - "&l&5Creative §eServer:kora.ddns.net:19134:url:i.imgur.com/8pbNECc.png"
  - "&l&4PvP §eServer:kora.ddns.net:19135:url:i.imgur.com/trtUAqx.png"
  - "&l&3Sky§cBlock §eServer:kora.ddns.net:19136:url:i.imgur.com/8WbhbeY.png"
